from utils_constants import DURATION_H_MS, DURATION_MIN_MS

MEASURE_INTERVAL_MS = const(10000)

DURATION_REGENERATE_MS = 2 * DURATION_H_MS
DURATION_DRY_MS = 2 * DURATION_H_MS

HEATER_BOARD_MAX = 110.0

# Statemachine
SM_REGENERATE_DIFF_DEW_C = const(10.0)

SM_DRYWAIT_DIFF_DEW_C = const(3.0)

SM_DRYFAN_NEXT_MS = DURATION_MIN_MS  # Interval of elements in list
SM_DRYFAN_ELEMENTS = const(10)  # 10min = 10 * 1min
SM_DRYFAN_DIFF_DEW_C = 0.5
SM_DRYFAN_DEW_SET_C = -100.0
