class LogfileTags:
    SM_STATE = "SM_STATE"
    SENSORS_HEADER = "SENSORS_HEADER"
    SENSORS_UNITS = "SENSORS_UNITS"
    SENSORS_VALUES = "SENSORS_VALUES"
    LOG_ERROR = "LOG_ERROR"
    LOG_WARNING = "LOG_WARNING"
    LOG_INFO = "LOG_INFO"
    LOG_DEBUG = "LOG_DEBUG"
